apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumes:
            - name: nginx-templates
              volumePath: /etc/nginx/templates
          env:
            - name: YOUR_NAME
              value: world
      volumes:
        - name: nginx-templates
          hostPath:
            path: ./nginx-templates
