apiVersion: batch/v1
kind: Job
metadata:
  name: curl-job
spec:
  template:
    spec:
      containers:
        - name: curl-container
          image: alpine
          command: ["/bin/sh"]
          args: ["-c", "echo $(curl http://my-nginx-service/)"]
      restartPolicy: Never
  backoffLimit: 4
